name: NPM Release (canary)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - run: pnpm install
      - name: Bump version
        run: npm --no-git-tag-version version "$(npm --no-git-tag-version version minor)-alpha.${{ github.run_number }}"
      - run: pnpm run build
      - run: pnpm publish --tag canary --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
